/* =============================================================================
   SETTINGS SAFETY
   -----------------------------------------------------------------------------
   Covers the settings whose stored value can leave the app in a state you
   cannot fix from inside the app: text too large to read the Settings modal,
   a startup view that doesn't exist, a notification sound file that isn't there,
   a button/modal cue the generated manifest promises but the folder no longer
   has.
============================================================================= */

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { ROOT, read, exists, slice, selectOptions, tagAttr } from "./_source.mjs";

test("the font size limit in code matches the limit on the input (text can't be made unreadable)", () => {
  // font scale feeds the root font size directly. A value of 500 renders the
  // whole app at ~520px, at which point the control that would undo it cannot
  // be read. The number input's min/max used to be the only thing enforcing it,
  // and a number input does not stop an out-of-range value being typed.
  const shell = read("src/core/shell.ts");
  const min = Number(/FONT_SCALE_MIN = (-?\d+)/.exec(shell)[1]);
  const max = Number(/FONT_SCALE_MAX = (-?\d+)/.exec(shell)[1]);
  assert.equal(min, Number(tagAttr("fontScaleValue", "min")), "code min != input min");
  assert.equal(max, Number(tagAttr("fontScaleValue", "max")), "code max != input max");
  assert.ok(min < 0 && max > 0, "range should span either side of the default");
});

test("the font size is clamped when loaded from disk, not just when typed", () => {
  const shell = read("src/core/shell.ts");
  assert.match(
    shell,
    /fontScale: clampFontScale\(merged\.fontScale\)/,
    "loadSettings must clamp, or a hand-edited settings file bypasses the limit",
  );
  assert.match(
    shell,
    /settings\.fontScale = clampFontScale\(/,
    "the input handler must clamp, or an out-of-range typed value is saved as-is",
  );
});

test("every startup view the app offers actually leads somewhere", () => {
  // Each option is either a mode, a section that exists in the page, or a
  // "section:tool" pair. Anything else opens to an empty window.
  const html = read("index.html");
  const modes = ["lastView", "lastTool", "lastCategory", "home"];
  const sections = new Set(
    [...html.matchAll(/id="section-([a-z-]+)"/g)].map((m) => m[1]),
  );
  const tools = new Set(
    [...slice("src/core/shell.ts", "const ALL_TOOLS", "];").matchAll(
      /section: "([a-z-]+)", tool: "([a-z-]+)"/g,
    )].map((m) => `${m[1]}:${m[2]}`),
  );

  for (const { value, label } of selectOptions("startupSelect")) {
    if (modes.includes(value)) continue;
    if (value.includes(":")) {
      assert.ok(tools.has(value), `startup option "${label}" points at unknown tool ${value}`);
    } else {
      assert.ok(sections.has(value), `startup option "${label}" points at unknown section ${value}`);
    }
  }
});

test("the startup dropdown lists exactly the tools the app has", () => {
  // Kept in sync by hand: nothing in the app reconciles these two lists.
  const tools = [...slice("src/core/shell.ts", "const ALL_TOOLS", "];").matchAll(
    /section: "([a-z-]+)", tool: "([a-z-]+)"/g,
  )].map((m) => `${m[1]}:${m[2]}`);
  const listed = selectOptions("startupSelect")
    .map((o) => o.value)
    .filter((v) => v.includes(":"));
  assert.deepEqual([...listed].sort(), [...tools].sort(), "ALL_TOOLS and the dropdown disagree");
});

test("every notification sound file the app references exists (otherwise alerts are silent)", () => {
  const block = slice("src/core/shell.ts", "const SOUND_PACKS", "];");
  // Paths in source are URLs, so decode any escapes before looking on disk.
  const files = [...block.matchAll(/"(\/sounds\/[^"]+)"/g)].map((m) => decodeURIComponent(m[1]));
  assert.ok(files.length > 0, "no sound files parsed, the check is not looking at the right block");
  const missing = files.filter((f) => !exists(`public${f}`));
  assert.deepEqual(missing, [], "these sound files are referenced but not on disk");
});

test("every button/modal cue the manifest lists exists on disk", () => {
  const text = read("src/sound/sound-manifest.ts");
  const urls = [...text.matchAll(/url: "(\/sounds\/[^"]+)"/g)].map((m) => decodeURIComponent(m[1]));
  const missing = urls.filter((u) => !exists(`public${u}`));
  assert.deepEqual(missing, [], "these cue files are listed in the manifest but not on disk");
});

test("the sound manifest is in step with the three cue folders", () => {
  // The manifest is generated by scripts/generate-sound-manifest.mjs from the
  // predev/prebuild hooks, so a stale one only survives if someone adds a file
  // and commits without running either. This catches that: the fix is to run
  // `node scripts/generate-sound-manifest.mjs`.
  const AUDIO = /\.(wav|mp3|ogg|m4a|flac|webm)$/i;
  const text = read("src/sound/sound-manifest.ts");

  for (const [folder, constName] of [
    ["button-sounds", "BUTTON_SOUNDS"],
    ["modal-sounds", "MODAL_SOUNDS"],
    ["timer-sounds", "TIMER_SOUNDS"],
  ]) {
    const dir = path.join(ROOT, "public", "sounds", folder);
    const onDisk = fs.existsSync(dir)
      ? fs
          .readdirSync(dir, { withFileTypes: true })
          .filter((e) => e.isFile() && AUDIO.test(e.name))
          .map((e) => e.name.replace(/\.[^.]+$/, ""))
          .sort()
      : [];

    const block = slice("src/sound/sound-manifest.ts", `export const ${constName}`, "];");
    const listed = [...block.matchAll(/\{ id: "([^"]+)"/g)].map((m) => m[1]).sort();

    assert.deepEqual(
      listed,
      onDisk,
      `${constName} disagrees with public/sounds/${folder}/ — re-run scripts/generate-sound-manifest.mjs`,
    );
  }
  assert.ok(text.includes("SoundEffect"), "the manifest is not the file this check expects");
});

test("every sound pack offers both a success and an error sound", () => {
  const block = slice("src/core/shell.ts", "const SOUND_PACKS", "];");
  const packs = [...block.matchAll(/\{\s*id: "([a-z0-9-]+)"[\s\S]*?\}/g)];
  assert.ok(packs.length > 0, "no sound packs parsed");
  for (const [entry, id] of packs.map((m) => [m[0], m[1]])) {
    assert.match(entry, /success:/, `sound pack "${id}" has no success sound`);
    assert.match(entry, /error:/, `sound pack "${id}" has no error sound`);
  }
});

test("no sound pack id shadows a reserved cue namespace", () => {
  // resolveSoundUrl() in sound.ts reads the part of a sound id before the
  // first colon. Three head words are reserved for the manifest-backed
  // folders and are matched BEFORE the pack list, so a pack that took one of
  // those ids would become unreachable as an alarm cue: "timer:success" would
  // be read as "the cue named success in timer-sounds/", not as that pack.
  // Renaming the pack is the fix; the namespaces are baked into stored
  // settings and cannot move.
  const reserved = [...read("src/sound/sound.ts").matchAll(/if \(head === "([a-z]+)"\) return/g)].map(
    (m) => m[1],
  );
  assert.ok(reserved.length >= 3, "could not parse the reserved namespaces out of sound.ts");

  const block = slice("src/core/shell.ts", "const SOUND_PACKS", "];");
  const packIds = [...block.matchAll(/\{\s*id: "([a-z0-9-]+)"/g)].map((m) => m[1]);
  assert.ok(packIds.length > 0, "no sound packs parsed");

  const clashes = packIds.filter((id) => reserved.includes(id));
  assert.deepEqual(clashes, [], `these pack ids collide with a reserved cue namespace (${reserved.join(", ")})`);
});

test("the Countdown Timer's default alarm names a cue that exists", () => {
  // A default that points at a missing file is a timer that rings silently,
  // and nothing else would catch it: the id is just a string until it is
  // played. Renaming a file in timer-sounds/ is what breaks this.
  const block = slice("src/tool/countdown.ts", "const DEFAULT_SETTINGS", "};");
  const m = /soundId: "([^"]+)"/.exec(block);
  assert.ok(m, "could not find the Countdown default soundId");
  const [head, ...rest] = m[1].split(":");
  const tail = rest.join(":");

  const manifest = read("src/sound/sound-manifest.ts");
  const packs = slice("src/core/shell.ts", "const SOUND_PACKS", "];");

  if (["timer", "button", "modal"].includes(head)) {
    const constName = `${head.toUpperCase()}_SOUNDS`;
    const listed = [...slice("src/sound/sound-manifest.ts", `export const ${constName}`, "];").matchAll(
      /\{ id: "([^"]+)"/g,
    )].map((x) => x[1]);
    assert.ok(
      listed.includes(tail),
      `Countdown's default alarm "${m[1]}" is not in ${constName} (have: ${listed.join(", ")})`,
    );
    assert.ok(manifest.includes("SoundEffect"), "the manifest is not the file this check expects");
  } else if (head !== "") {
    assert.match(
      packs,
      new RegExp(`id: "${head}"`),
      `Countdown's default alarm names sound pack "${head}", which is not in SOUND_PACKS`,
    );
  }
});

test("every renamed sound pack points at a pack that exists", () => {
  // RENAMED_SOUND_PACKS is what stops a folder rename from silently resetting
  // someone's sound pack and killing their timer alarm. A map entry that
  // points nowhere does none of that, and would fail just as quietly.
  const block = slice("src/core/shell.ts", "const RENAMED_SOUND_PACKS", "};");
  const entries = [...block.matchAll(/^\s*([a-z0-9-]+): "([a-z0-9-]+)",/gm)].map((m) => [m[1], m[2]]);

  const packBlock = slice("src/core/shell.ts", "const SOUND_PACKS", "];");
  const packIds = [...packBlock.matchAll(/\{\s*id: "([a-z0-9-]+)"/g)].map((m) => m[1]);

  for (const [from, to] of entries) {
    assert.ok(packIds.includes(to), `RENAMED_SOUND_PACKS maps "${from}" to "${to}", which is not a pack`);
    assert.ok(
      !packIds.includes(from),
      `"${from}" is both a live pack id and a rename source; the map would redirect it away from itself`,
    );
  }
});

test("the sidebar's About, Settings and collapse entries stay out of the button cue", () => {
  // BUTTON_CUE_INCLUDE in shell.ts reaches sidebar entries via
  // ".nav-item[data-section]". That selector is the whole mechanism keeping the
  // click cue off the three entries that are not tool navigation: About and
  // Settings open a modal, whose own cue says more than a click would, and the
  // collapse toggle is chrome. Giving any of them a data-section for some
  // unrelated reason would quietly opt them back in.
  const html = read("index.html");
  const navItems = [...html.matchAll(/<li[^>]*class="nav-item[^"]*"[^>]*>/g)].map((m) => m[0]);
  assert.ok(navItems.length > 5, "did not find the sidebar nav items");

  for (const id of ["aboutBtn", "settingsBtn", "sidebarToggle"]) {
    const tag = navItems.find((n) => n.includes(`id="${id}"`));
    assert.ok(tag, `#${id} is not a .nav-item any more; re-check the button cue selector`);
    assert.ok(
      !tag.includes("data-section"),
      `#${id} now carries data-section, so the button cue selector picks it up`,
    );
  }

  // And the inverse: the selector has to still reach real tool listings.
  const withSection = navItems.filter((n) => n.includes("data-section"));
  assert.ok(
    withSection.length >= 10,
    `only ${withSection.length} sidebar entries carry data-section; the cue selector may be matching nothing`,
  );
});

test("the Countdown alarm's Test button does not also fire the button cue", () => {
  // The Test button auditions the alarm through playSoundUrl(), which is
  // outside the priority gate on purpose (a preview must never be suppressed).
  // Nothing else would stop the click cue landing on top of it, so the id is
  // listed by hand in BUTTON_CUE_EXCLUDE and has to keep matching the markup.
  const exclude = slice("src/core/shell.ts", "const BUTTON_CUE_EXCLUDE", "].join");
  assert.match(exclude, /#cd-sound-test/, "BUTTON_CUE_EXCLUDE no longer excludes the alarm preview");
  assert.match(
    read("index.html"),
    /id="cd-sound-test"/,
    'the alarm preview button is not #cd-sound-test any more; BUTTON_CUE_EXCLUDE is now stale',
  );
});

test("every sound the app ships is credited in ATTRIBUTION.md", () => {
  // Not housekeeping: several of these are CC BY, where crediting the author
  // is a condition of the licence, not a courtesy. Adding a pack or dropping a
  // cue file into a folder is a two-second job that silently creates a
  // licensing gap, and nothing else in the build would notice.
  //
  // Deliberately loose about the entry's contents: it checks a heading exists
  // per sound, not that the author or URL is right. Those come from the
  // -attr.txt files that ship alongside the audio, which a human has to read.
  const attribution = read("ATTRIBUTION.md");
  const missing = [];

  const packBlock = slice("src/core/shell.ts", "const SOUND_PACKS", "];");
  const packNames = [...packBlock.matchAll(/name: "([^"]+)"/g)].map((m) => m[1]);
  assert.ok(packNames.length > 0, "no sound packs parsed");
  for (const name of packNames) {
    if (!attribution.includes(`### Sound Pack: ${name}`)) missing.push(`sound pack "${name}"`);
  }

  const cueNames = [...read("src/sound/sound-manifest.ts").matchAll(/name: "([^"]+)"/g)].map((m) => m[1]);
  assert.ok(cueNames.length > 0, "no manifest cues parsed");
  for (const name of cueNames) {
    if (!attribution.includes(`**${name}**`)) missing.push(`cue "${name}"`);
  }

  assert.deepEqual(
    missing,
    [],
    "these ship in the app but have no entry in ATTRIBUTION.md; the credit lines are in the -attr.txt file in each sound folder",
  );
});

test("the app lock cannot be left in a state with no way back in", () => {
  // A lock.json that exists but is corrupt used to gate the app behind a screen
  // that no credential could satisfy, with Change/Remove sitting behind that
  // same lock. Startup must test the stored hash is USABLE, not just present.
  const rs = read("src-tauri/src/lib.rs");
  assert.match(
    rs,
    /fn lock_is_set\([^)]*\)\s*->\s*bool\s*\{\s*read_valid_lock_hash\(&app\)\.is_some\(\)/,
    "lock_is_set must validate the stored hash, not just check the file exists",
  );
  assert.match(
    rs,
    /parsed\.hash\.is_some\(\) && parsed\.salt\.is_some\(\)/,
    "a truncated hash still parses; the digest and salt must both be required",
  );
});
